server:
  port: 5009

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.33.237:3306/mc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: mc
    password: Root!123



#    #上传文件总的最大值
#    servlet:
#      multipart:
#        max-request-size: 1000MB
#        #上传文件的最大值
#        max-file-size: 1000MB

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#上传物理路径
file:
  upload:
    path: D:/upfiles/
    #虚拟路径
    relative: files/**